DataLake_iceberg_poc:
  target: dev
  outputs:
    dev:
      type: glue
      aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      role_arn: arn:aws:iam::680736395115:role/dbt_glue_service_role
      region: us-west-1
      workers: 5
      worker_type: G.1X
      schema: staging_fast_gitactions
      database: staging_fast_gitactions
      session_provisioning_timeout_in_seconds: 500
      location: "s3://aaa-poc-glue-data-us-west-1/hudi"
      connections: "dbt_glue_hudi_connection"
      conf: "spark.serializer=org.apache.spark.serializer.KryoSerializer"
