name: DBT Workflow

on:
  push:
    branches:
      - DF-263/git_actions_with_dbt

jobs:
  dbt_job:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install DBT
      run: |
          pip install dbt-core==1.4.2
          pip install dbt-glue==1.4.23
    
    - name: Dbt debug
      run: dbt debug

    - name: DBT Run
      run: dbt run
